language: ruby


rvm:
  - 1.9.3
  - 2.1.1


env:
 global:  
  - TEST_CONFIG=test_mysql
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage


gemfile:
  - gemfiles/Gemfile.rails-3.2.x

  
before_script:
  - sh -c "if [ '$TEST_CONFIG' = 'test_mysql' ]; then mysql -e 'create database mygem_test;' --user=root;  fi"
  - sh -c "if [ '$TEST_CONFIG' = 'test_postgres' ]; then psql -c 'create database myapp_test;' -U postgres; fi"
  - echo $BRANCH

notifications:
  email: buildsampletest@gmail.com
